---
version: "3.8"
services:
  tomcat:
    image: tomcat
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: vol8
        target: /usr/local/tomcat/webapps

    depends_on:
      - maven

  maven:
    build: maven-custom
    volumes:
      - type: volume
        source: vol8
        target: /root/boxfuse-sample-java-war-hello/target

volumes:
  vol8:
