---
version: "3.8"
services:
  tomcat:
    image: nirmata/tomcat9-alpine-jre12-openj9
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: vol4
        target: /opt/apache-tomcat-9.0.31/webapps
    depends_on:
      - maven

  maven:
    build: maven-custom
    volumes:
      - type: volume
        source: vol4
        target: /root/boxfuse-sample-java-war-hello/target

volumes:
  vol4:
