---
version: "3.8"
services:
  tomcat:
    image: nirmata/tomcat9-alpine-jre12-openj9
    ports:
      - "8080:8080"
    volumes_from:
      - home7_maven_1
    depends_on:
      - maven

  maven:
    build: maven-custom
    volumes:
      - type: volume
        source: vol6
        target: /root/boxfuse-sample-java-war-hello/target

volumes:
  vol6:
