---
version: "3.8"
services:
  tomcat:
    image: nirmata/tomcat9-alpine-jre12-openj9
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: shared
        target: /webapps

  maven:
    build: maven-custom
    volumes:
      - type: volume
        source: shared
        target: /root/boxfuse-samle-java-war-hello/target

volumes:
  shared:
